django_templates_project/django_templates_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("template_app.urls")),
    path('admin/', admin.site.urls),
    path("", include("django.contrib.auth.urls")),
]

django_templates_project/template_app/urls.py
from django.urls import path
from . import views

app_name="template_app"


urlpatterns = [
    path('', views.index, name="index"),
    path("weather/",views.weather_view,name="weatherview"),
    path("index/",views.database,name="databaseview"),
    path("addtweet/",views.addtweet,name="addtweet"),
    path("listtweet/",views.listtweet,name="listtweet"),
    path("addtweetbyform/",views.addtweetbyform,name="addtweetbyform"),
    path("addtweetbymodelform/",views.addtweetbymodelform,name="addtweetbymodelform"),
    path("register/",views.Register.as_view(),name="register"),
    path("deletetweet/<int:id>",views.deletetweet,name="deletetweet"),
]

django_templates_project/template_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
# Create your models here.
class Musician(models.Model):
    name=models.CharField(max_length=50)
    instrument=models.CharField(max_length=50)
    age=models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(150)])
    salary= models.IntegerField(default=0,validators=[MinValueValidator(0)])

class Tweet(models.Model):
    username=models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    message=models.CharField(max_length=200)

    def __str__(self):
        return f"Tweet user: {self.username} message : {self.message}"

django_templates_project/template_app/forms.py
from django import forms
from template_app.models import Tweet
from django.forms import ModelForm

class AddTweetForm(forms.Form):
    nickname_input = forms.CharField(label="Nickname",max_length=50)
    message_imput = forms.CharField(label="message",max_length=100,
                                    widget=forms.Textarea(attrs={"class":"tweetmessage"}))
    
class AddTweetModelForm(ModelForm):
    class Meta:
        model = Tweet
        fields =["username","message"]

django_templates_project/template_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from . import models
from template_app.forms import AddTweetForm, AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView


# Create your views here.
def index(request):
    return render(request,"template_app/first.html")

def weather_view(request):
    weather_dic={"istanbul": "30", "amsterdam" : "20",
                "paris":[10,20,30,40]
                 }
    return render(request,"template_app/weather.html",context=weather_dic)

def database(request):
    musician_data=models.Musician.objects.all().values()
    data_view={"musicians":musician_data}
    return render(request,"template_app/index.html",context=data_view)

def listtweet(request):
    tweets_data=models.Tweet.objects.all()
    tweet_dict={"tweets":tweets_data}
    return render(request,"template_app/listtweet.html",context=tweet_dict)

@login_required(login_url="/login")
def addtweet(request):
    if request.POST:
        message= request.POST["message"]
        models.Tweet.objects.create(username=request.user,message=message)
        #tweet = models.Tweet(nickname,message)
        #tweet.save()
        return redirect(reverse('template_app:listtweet'))
    else:
        return render(request,"template_app/addtweet.html")
    
def addtweetbyform(request):
    if request.POST:
        form=AddTweetForm(request.POST)
        if form.is_valid():
            nickname= request.POST["nickname_input"]
            message= request.POST["message_imput"]
            models.Tweet.objects.create(nickname=nickname,message=message)
            return redirect(reverse('template_app:listtweet'))
        else:
            print("error is form")
            return render(request,'template_app/addtweetbyform.html',context={"form":form})
    else:
        form=AddTweetForm()
        return render(request,'template_app/addtweetbyform.html',context={"form":form})
    
def addtweetbymodelform(request):
    if request.POST:
        form=AddTweetModelForm(request.POST)
        if form.is_valid():
           nickname= request.POST["nickname"]
           message= request.POST["message"]
           models.Tweet.objects.create(nickname=nickname,message=message)
           return redirect(reverse('template_app:listtweet'))
        else:
            print("error is form")
            return render(request,'template_app/addtweetbymodelform.html',context={"form":form})
    else:
        form=AddTweetModelForm()
        return render(request,'template_app/addtweetbymodelform.html',context={"form":form})
@login_required
def deletetweet(request,id):
    tweet =models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect('template_app:listtweet')
    



class Register(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name= "registration/register.html"

django_templates_project/template_app/templates/template_app/addtweet.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link href="{% static 'template_app/custom.css' %}" rel="stylesheet">
<h2>ADD TWEET PAGE</h2>
<form action=""  method="POST">
    {% csrf_token %}
  <!--
  <div class="input-group mb-3">
    <span class="input-group-text" id="basic-addon1">@</span>
    <input type="text" class="form-control" name= "Username" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
  </div>
  -->
  <div class="mb-3">
    <label for="message" class="form-label">Example textarea</label>
    <textarea class="form-control" id="message" name= "message" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock  %}

django_templates_project/template_app/templates/template_app/addtweetbyform.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link href="{% static 'template_app/custom.css' %}" rel="stylesheet">
<h2>ADD TWEETFORM PAGE</h2>
<form action=""  method="POST">
    {% csrf_token %}
  <div class="mb-3">
  {{form.nickname_input.label_tag}}
  {{form.nickname_input}}
</div>
  <div class="mb-3">
  {{form.message_imput.label_tag}}
  {{form.message_imput}}
</div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock  %}

django_templates_project/template_app/templates/template_app/addtweetbymodelform.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link href="{% static 'template_app/custom.css' %}" rel="stylesheet">
<h2>ADD TWEETFORM PAGE</h2>
<form action=""  method="POST">
    {% csrf_token %}

  {% for i in form %}
  <div class="mb-3">
      {{i.label_tag}}
      {{i}}
  </div>
    {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock  %}

django_templates_project/template_app/templates/template_app/first.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!--<img src="{% static 'template_app/yapayzeka.jpeg' %}" alt="My image"> 
<h2><a href="{% url 'template_app:weatherview' %}">go to weather</h2>-->
    <link href="{% static 'template_app/custom.css' %}" rel="stylesheet">
   
    <div class="container">
<form>
        {% for tweet in tweets %}
        <div class="card" style="padding:10px;">
          <div class="card-header" style="background-color: rgb(86, 114, 197);">
            <h5>@{{tweet.nickname}}</h5>
          </div>
          <div class="card-body">
            <p class="card-text">{{tweet.message}}</p>
          </div>
        </div>  
        {% endfor %}  
    </div>
</form>



{% endblock  %}

django_templates_project/template_app/templates/template_app/index.html
{% extends 'base.html' %}

{% block content %}


<ul>
    {% for i in musicians %}
    
        <li>Name: {{ i.name }}  İnstrument:  {{i.instrument}}   Age:  {{i.age}}    Salary:  {{i.salary}} </li>

    {% endfor %}
</ul>

{% endblock  %}

django_templates_project/template_app/templates/template_app/listtweet.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  
    {% for tweet in tweets %}
    <div class="card" style="padding:10px;">
      <div class="card-header" style="background-color: rgb(86, 114, 197);">
        <h5>@{{tweet.username}}</h5>
      </div>
      <div class="card-body">
        <p class="card-text">{{tweet.message}}</p>
      </div>
      {%if tweet.username == user%}
      <a href="{% url 'template_app:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>
      {%endif%}
    </div>  
      

    {% endfor %}  
</div>

    
 
{% endblock  %}

django_templates_project/template_app/templates/template_app/weather.html
{% extends 'base.html' %}
{% block content %}
    <h1>weather report</h1>
    <h2>istanbul: {{istanbul}}</h2>
    <br>
    {% for item in paris %}
    
        <p>{{item}} </p>
    
    {% endfor %}

    <h2><a href="{% url 'template_app:index' %}">go to index</h2>

{% endblock  %}

django_templates_project/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Tweet App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <body style="background-color:rgba(236, 236, 231, 0.738);"></body>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
          z-index: 1500;
        }
        body {
            min-height: 75rem;
            padding-top: 4.5rem;
        }
      </style>
  


</head>
  <body>
    <h1></h1>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'template_app:listtweet' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'template_app:addtweet' %}">Addtweet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'template_app:listtweet' %}">Listtweet</a>
              </li>
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'template_app:weatherview' %}">Weather</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'template_app:addtweetbyform' %}">Addtweetform</a>
              </li>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'template_app:addtweetbymodelform' %}">addtweetbymodelform</a>
            </li>
            -->
            </ul>
            <form class="d-flex" role="search">
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'template_app:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'logout' %}?next=/listtweet/">Logout</a>
              </li>
            </form>
          </div>
        </div>
      </nav>
      {% block content  %}
      
      {% endblock  %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>